name: release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-linux-musl
            name: duct-x86_64
            static: true
          - target: aarch64-linux-musl
            name: duct-aarch64
            static: true
          - target: arm-linux-musleabihf
            name: duct-armhf
            static: true
          - target: riscv64-linux-musl
            name: duct-riscv64
            static: true
          - target: i386-linux-musl
            name: duct-i386
            static: true
          - target: x86_64-linux-gnu
            name: duct-x86_64-glibc
            static: false
          - target: i386-linux-gnu
            name: duct-i386-glibc
            static: false
          - target: aarch64-linux-android
            name: duct-aarch64-android
            static: true
          - target: arm-linux-androideabi
            name: duct-arm-android
            static: true
          - target: x86_64-linux-android
            name: duct-x86_64-android
            static: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: |
          flags="-target ${{ matrix.target }} -O2 -s"
          ${{ matrix.static }} && flags="$flags -static"
          zig cc $flags -o ${{ matrix.name }} duct.c
          strip ${{ matrix.name }} || true
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: binaries
          merge-multiple: true
      - run: |
          cd binaries
          sha256sum * > SHA256SUMS
      - uses: softprops/action-gh-release@v2
        with:
          files: binaries/*
          generate_release_notes: true
